version: '3.7'

services:
  redis:
    image: redis

    container_name: redis

    ports:
      - "6379:6379"

    command: ["redis-server"]
    
  web:
    build: 
      context: .
      dockerfile: dockerfile

      environment:
        - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
        - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_KEY=${AWS_SECRET_KEY}

        - AWS_RDS_HOST= ${AWS_RDS_HOST}
        - AWS_RDS_USER= ${AWS_RDS_USER}
        - AWS_RDS_DATABASE= ${AWS_RDS_DATABASE}
        - AWS_RDS_PASSWORD= ${AWS_RDS_PASSWORD}

        - port= ${PORT}



    image: interaction
    
    ports:
      - "3000:3000"

    volumes:
      - "/tmp/record:/tmp/record"

    depends_on:
      - redis

    command: ["npm", "start"]

