version: '3.7'

services:
  redis:
    image: redis

    container_name: redis

    ports:
      - "6379:6379"

    restart: always
    
    command: ["redis-server"]
    
  web:
    build: 
      context: .
      dockerfile: dockerfile

    image: interaction
    
    ports:
      - "3005:3005"

    volumes:
      - "/tmp/record:/tmp/record"

    depends_on:
      - redis

    command: ["npm", "start"]

