version: '3.7'

services:
  redis:
    image: redis

    container_name: redis

    ports:
      - "6379:6379"

    restart: always

    networks:
      - my-network
    
    command: ["redis-server"]
    
  web:
    build: 
      context: .
      dockerfile: dockerfile

    image: interaction
    
    ports:
      - "3000:3000"

    volumes:
      - "/tmp/record:/tmp/record"

    depends_on:
      - redis

    networks:
      - my-network

    command: ["npm", "start"]

  nginx-rtmp:
    restart: always

    image: tiangolo/nginx-rtmp

    container_name: nginx-rtmp

    ports:
      - "1935:1935"
      
    volumes:
      - "./nginx-rtmp.conf:/etc/nginx/nginx.conf:ro"
      - "/tmp/record:/tmp/record"
      - "/tmp/hls:/tmp/hls"
      
    depends_on:
      - web
 
    networks:
      - my-network

  nginx:
    restart: always

    image: nginx

    container_name: nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/.well-known/pki-validation/:/var/tmp/.well-known/pki-validation/"
      - "/var/projects/ssl:/var/projects/ssl"
      - "/tmp/record:/tmp/record"
      - "/tmp/hls:/tmp/hls"

    depends_on:
      - web
 
    networks:
      - my-network

networks:
  my-network:
    driver: bridge