name: backend CI/CD Pipeline

on:
  push:
    branches: ['main']
env:
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME}}
  AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION}}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY}}

  AWS_RDS_HOST: ${{ secrets.AWS_RDS_HOST}}
  AWS_RDS_USER: ${{ secrets.AWS_RDS_USER}}
  AWS_RDS_DATABASE: ${{ secrets.AWS_RDS_DATABASE}}
  AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD}}

  port: ${{ secrets.PORT}}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH into EC2 and update Dcoker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOSTNAME }}
          username: ${{secrets.AWS_USERNAME }}
          key: ${{secrets.AWS_PRIVATE_KEY }}
          script: |
            docker-compose down
            cd /interaction
            sudo git pull
            docker build -t interaction .
            echo "y" | docker system prune
            docker-compose up -d