name: backend CI/CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH into EC2 and update Dcoker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOSTNAME }}
          username: ${{secrets.AWS_USERNAME }}
          key: ${{secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /interaction
            docker-compose down
            # sudo git pull
            # docker build -t interaction .
            # echo "y" | docker system prune
            # docker-compose up -d